# Generated by Django 5.2.4 on 2025-08-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partnerek'},
        ),
        migrations.AddField(
            model_name='partner',
            name='institution',
            field=models.CharField(choices=[('iskola', 'Iskola'), ('kutatóintézet', 'Kutatóintézet'), ('kozossegi_haz', 'Közösségi Ház'), ('kulturalis_kozpont', 'Kulturális Központ'), ('muzeum', 'Múzeum'), ('konyvtar', 'Könyvtár'), ('egyesulet', 'Egyesület'), ('vallalat', 'Vállalat'), ('onkormanyzat', 'Önkormányzat'), ('egyéb', 'Egyéb')], default='egyeb', max_length=150),
        ),
    ]
