# Generated by Django 5.2.4 on 2025-08-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_partner_options_partner_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='institution',
            field=models.CharField(choices=[('iskola', 'Iskola'), ('kutatóintézet', 'Kutatóintézet'), ('kozossegi_haz', 'Közösségi Ház'), ('kulturalis_kozpont', 'Kulturális Központ'), ('muzeum', 'Múzeum'), ('konyvtar', 'Könyvtár'), ('egyesulet', 'Egyesület'), ('vallalat', 'Vállalat'), ('onkormanyzat', 'Önkormányzat'), ('egyeb', 'Egyéb')], default='egyeb', max_length=150),
        ),
    ]
