# Generated by Django 5.2.4 on 2025-08-08 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_partner_institution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('allowEmails', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Konfiguráció',
                'verbose_name_plural': 'Konfigurációk',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Kapcsolattartó',
                'verbose_name_plural': 'Kapcsolattartók',
            },
        ),
        migrations.CreateModel(
            name='EquipmentTipus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('emoji', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Eszköz Típus',
                'verbose_name_plural': 'Eszköz Típusok',
            },
        ),
        migrations.CreateModel(
            name='Osztaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startYear', models.IntegerField()),
                ('szekcio', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerTipus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Partner Típus',
                'verbose_name_plural': 'Partner Típusok',
            },
        ),
        migrations.CreateModel(
            name='Stab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Stáb',
                'verbose_name_plural': 'Stábok',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='imgUrl',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150, unique=True)),
                ('brand', models.CharField(blank=True, max_length=150, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('serialNumber', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('functional', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('equipmentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='api.equipmenttipus')),
            ],
            options={
                'verbose_name': 'Felaszerelés',
                'verbose_name_plural': 'Felaszerelések',
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='Forgatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('timeFrom', models.TimeField()),
                ('timeTo', models.TimeField()),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('forgTipus', models.CharField(choices=[('kacsa', 'KaCsa'), ('rendes', 'Rendes'), ('rendezveny', 'Rendezvény'), ('egyeb', 'Egyéb')], max_length=150)),
                ('contactPerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.contactperson')),
                ('equipments', models.ManyToManyField(blank=True, related_name='forgatasok', to='api.equipment')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.partner')),
                ('relatedKaCsa', models.ForeignKey(blank=True, limit_choices_to={'forgTipus': 'kacsa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_forgatas', to='api.forgatas')),
            ],
            options={
                'verbose_name': 'Forgatás',
                'verbose_name_plural': 'Forgatások',
                'ordering': ['date', 'timeFrom'],
            },
        ),
        migrations.AlterField(
            model_name='partner',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='api.partnertipus'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonszam', models.CharField(blank=True, max_length=20, null=True)),
                ('medias', models.BooleanField(default=True)),
                ('osztaly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.osztaly')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagok', to='api.stab')),
            ],
        ),
    ]
