# Generated by Django 5.2.5 on 2025-08-08 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_config_contactperson_equipmenttipus_osztaly_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Szerepkor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('ev', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Szerepkör',
                'verbose_name_plural': 'Szerepkörök',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('cimzettek', models.ManyToManyField(blank=True, related_name='uzenetek', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Közlemény',
                'verbose_name_plural': 'Közlemények',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SzerepkorRelaciok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szerepkor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.szerepkor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Szerepkör Reláció',
                'verbose_name_plural': 'Szerepkör Relációk',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Beosztas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kesz', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beosztasok', to=settings.AUTH_USER_MODEL)),
                ('szerepkor_relaciok', models.ManyToManyField(blank=True, related_name='beosztasok', to='api.szerepkorrelaciok')),
            ],
            options={
                'verbose_name': 'Beosztás',
                'verbose_name_plural': 'Beosztások',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tavollet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, max_length=500, null=True)),
                ('denied', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Távollét',
                'verbose_name_plural': 'Távollétek',
                'ordering': ['start_date'],
            },
        ),
    ]
