# Generated by Django 5.2.4 on 2025-08-09 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_szerepkor_announcement_szerepkorrelaciok_beosztas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beosztas',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beosztasok', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipmentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='api.equipmenttipus'),
        ),
        migrations.AlterField(
            model_name='forgatas',
            name='contactPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.contactperson'),
        ),
        migrations.AlterField(
            model_name='forgatas',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.partner'),
        ),
        migrations.AlterField(
            model_name='forgatas',
            name='relatedKaCsa',
            field=models.ForeignKey(blank=True, limit_choices_to={'forgTipus': 'kacsa'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_forgatas', to='api.forgatas'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='api.partnertipus'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='osztaly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.osztaly'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tagok', to='api.stab'),
        ),
    ]
