# Generated by Django 5.2.4 on 2025-08-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_announcement_author_alter_beosztas_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_type',
            field=models.CharField(choices=[('none', 'Nincs adminisztrátor jogosultság'), ('developer', 'Administrator-Developer'), ('teacher', 'Administrator-Teacher (Médiatanár)')], default='none', max_length=20, verbose_name='Adminisztrátor típus'),
        ),
    ]
