# Generated by Django 5.2.4 on 2025-08-09 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_admin_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioStab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Stáb név')),
                ('team_code', models.CharField(choices=[('A1', 'A1 rádió csapat'), ('A2', 'A2 rádió csapat'), ('B3', 'B3 rádió csapat'), ('B4', 'B4 rádió csapat')], max_length=2, unique=True, verbose_name='Csapat kód')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Leírás')),
            ],
            options={
                'verbose_name': 'Rádiós Stáb',
                'verbose_name_plural': 'Rádiós Stábok',
                'ordering': ['team_code'],
            },
        ),
        migrations.CreateModel(
            name='RadioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dátum')),
                ('time_from', models.TimeField(verbose_name='Kezdés ideje')),
                ('time_to', models.TimeField(verbose_name='Befejezés ideje')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Leírás')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='radio_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Résztvevők')),
                ('radio_stab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.radiostab', verbose_name='Rádiós stáb')),
            ],
            options={
                'verbose_name': 'Rádiós összejátszás',
                'verbose_name_plural': 'Rádiós összejátszások',
                'ordering': ['date', 'time_from'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='radio_stab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tagok', to='api.radiostab', verbose_name='Rádiós stáb'),
        ),
    ]
