# Generated by Django 5.2.4 on 2025-08-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_radiostab_radiosession_profile_radio_stab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osztaly',
            options={'ordering': ['startYear', 'szekcio'], 'verbose_name': 'Osztály', 'verbose_name_plural': 'Osztályok'},
        ),
        migrations.CreateModel(
            name='Tanev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='A tanév kezdő dátuma (pl. 2024-09-01)', verbose_name='Kezdő dátum')),
                ('end_date', models.DateField(help_text='A tanév záró dátuma (pl. 2025-06-13)', verbose_name='Záró dátum')),
                ('osztalyok', models.ManyToManyField(blank=True, help_text='A tanévhez tartozó osztályok', related_name='tanevek', to='api.osztaly', verbose_name='Osztályok')),
            ],
            options={
                'verbose_name': 'Tanév',
                'verbose_name_plural': 'Tanévek',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='beosztas',
            name='tanev',
            field=models.ForeignKey(blank=True, help_text='A beosztás tanéve', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tanev', verbose_name='Tanév'),
        ),
        migrations.AddField(
            model_name='forgatas',
            name='tanev',
            field=models.ForeignKey(blank=True, help_text='A forgatás tanéve (automatikusan meghatározva a dátum alapján)', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tanev', verbose_name='Tanév'),
        ),
        migrations.AddField(
            model_name='osztaly',
            name='tanev',
            field=models.ForeignKey(blank=True, help_text='Az a tanév, amikor ez az osztály aktív volt/lesz', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tanev', verbose_name='Tanév'),
        ),
        migrations.AddField(
            model_name='radiosession',
            name='tanev',
            field=models.ForeignKey(blank=True, help_text='A rádiós összejátszás tanéve (automatikusan meghatározva a dátum alapján)', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tanev', verbose_name='Tanév'),
        ),
    ]
