# Generated by Django 5.2.4 on 2025-08-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_osztaly_options_tanev_beosztas_tanev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_login_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Első bejelentkezés token küldve'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_login_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Első bejelentkezés token'),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_set',
            field=models.BooleanField(default=False, verbose_name='Jelszó beállítva'),
        ),
        migrations.AddField(
            model_name='profile',
            name='special_role',
            field=models.CharField(choices=[('none', 'Nincs különleges szerep'), ('production_leader', 'Gyártásvezető')], default='none', max_length=20, verbose_name='Különleges szerep'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='admin_type',
            field=models.CharField(choices=[('none', 'Nincs adminisztrátor jogosultság'), ('developer', 'Administrator-Developer'), ('teacher', 'Administrator-Teacher (Médiatanár)'), ('system_admin', 'Rendszeradminisztrátor')], default='none', max_length=20, verbose_name='Adminisztrátor típus'),
        ),
    ]
