# Generated by Django 5.2.4 on 2025-08-11 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_first_login_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timeFrom', models.TimeField()),
                ('timeTo', models.TimeField()),
                ('excused', models.BooleanField(default=False)),
                ('unexcused', models.BooleanField(default=False)),
                ('diak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forgatas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forgatas')),
            ],
            options={
                'verbose_name': 'Hiányzás',
                'verbose_name_plural': 'Hiányzások',
            },
        ),
    ]
