# Generated by Django 5.2.4 on 2025-08-12 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_absence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='osztaly',
            name='osztaly_fonokei',
            field=models.ManyToManyField(blank=True, help_text='Az osztály fő- és helyettes osztályfőnökei', related_name='osztaly_fonokei', to=settings.AUTH_USER_MODEL, verbose_name='Osztályfőnökei'),
        ),
        migrations.AddField(
            model_name='profile',
            name='osztalyfonok',
            field=models.BooleanField(default=False, verbose_name='Osztályfőnök'),
        ),
    ]
