# Generated by Django 5.2.4 on 2025-08-12 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_equipment_scheduling_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='beosztas',
            name='forgatas',
            field=models.ForeignKey(blank=True, help_text='A beosztáshoz tartozó forgatás', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beosztasok', to='api.forgatas', verbose_name='Forgatás'),
        ),
    ]
