# Generated by Django 5.2.4 on 2025-08-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_beosztas_forgatas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['nickname'], 'verbose_name': 'Felszerelés', 'verbose_name_plural': 'Felszerelések'},
        ),
    ]
