# Generated by Django 5.2.4 on 2025-08-14 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_equipment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='date',
            field=models.DateField(help_text='A hiányzás dátuma', verbose_name='Dátum'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='diak',
            field=models.ForeignKey(help_text='A hiányzó diák', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Diák'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='excused',
            field=models.BooleanField(default=False, help_text='Jelöli, hogy a hiányzás igazolt-e', verbose_name='Igazolt'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='forgatas',
            field=models.ForeignKey(help_text='A forgatás, ami miatt hiányzik', on_delete=django.db.models.deletion.CASCADE, to='api.forgatas', verbose_name='Forgatás'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='timeFrom',
            field=models.TimeField(help_text='A hiányzás kezdési időpontja', verbose_name='Kezdés ideje'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='timeTo',
            field=models.TimeField(help_text='A hiányzás befejezési időpontja', verbose_name='Befejezés ideje'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='unexcused',
            field=models.BooleanField(default=False, help_text='Jelöli, hogy a hiányzás igazolatlan-e', verbose_name='Igazolatlan'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(blank=True, help_text='A közlemény szerzője', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Szerző'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=models.TextField(help_text='A közlemény tartalma (maximum 5000 karakter)', max_length=5000, verbose_name='Tartalom'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='cimzettek',
            field=models.ManyToManyField(blank=True, help_text='A közlemény címzettjei', related_name='uzenetek', to=settings.AUTH_USER_MODEL, verbose_name='Címzettek'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='A közlemény létrehozásának időpontja', verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(help_text='A közlemény címe (maximum 200 karakter)', max_length=200, verbose_name='Cím'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='A közlemény utolsó módosításának időpontja', verbose_name='Módosítva'),
        ),
        migrations.AlterField(
            model_name='beosztas',
            name='author',
            field=models.ForeignKey(blank=True, help_text='A beosztást végző felhasználó', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beosztasok', to=settings.AUTH_USER_MODEL, verbose_name='Szerző'),
        ),
        migrations.AlterField(
            model_name='beosztas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='A beosztás létrehozásának időpontja', verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='beosztas',
            name='kesz',
            field=models.BooleanField(default=False, help_text='Jelöli, hogy a beosztás elkészült és végleges-e', verbose_name='Kész'),
        ),
        migrations.AlterField(
            model_name='beosztas',
            name='szerepkor_relaciok',
            field=models.ManyToManyField(blank=True, help_text='A beosztáshoz tartozó szerepkör hozzárendelések', related_name='beosztasok', to='api.szerepkorrelaciok', verbose_name='Szerepkör relációk'),
        ),
        migrations.AlterField(
            model_name='config',
            name='active',
            field=models.BooleanField(default=False, help_text='Jelöli, hogy a rendszer aktív-e', verbose_name='Aktív'),
        ),
        migrations.AlterField(
            model_name='config',
            name='allowEmails',
            field=models.BooleanField(default=False, help_text='Jelöli, hogy a rendszer küldhet-e e-maileket', verbose_name='E-mailek engedélyezése'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(blank=True, help_text='A kapcsolattartó e-mail címe (opcionális)', max_length=254, null=True, verbose_name='E-mail cím'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name',
            field=models.CharField(help_text='A kapcsolattartó személy teljes neve', max_length=150, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='phone',
            field=models.CharField(blank=True, help_text='A kapcsolattartó telefonszáma (opcionális)', max_length=20, null=True, verbose_name='Telefonszám'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.CharField(blank=True, help_text='Az eszköz gyártójának neve', max_length=150, null=True, verbose_name='Márka'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipmentType',
            field=models.ForeignKey(blank=True, help_text='Az eszköz kategóriája', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='api.equipmenttipus', verbose_name='Eszköz típusa'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='functional',
            field=models.BooleanField(default=True, help_text='Jelöli, hogy az eszköz használható állapotban van-e', verbose_name='Működőképes'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, help_text='Az eszköz modell neve vagy száma', max_length=150, null=True, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='nickname',
            field=models.CharField(help_text='Az eszköz egyedi beceneve (azonosításhoz)', max_length=150, verbose_name='Becenév'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, help_text='További információk az eszközről (maximum 500 karakter)', max_length=500, null=True, verbose_name='Megjegyzések'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serialNumber',
            field=models.CharField(blank=True, help_text='Az eszköz gyári sorozatszáma (egyedi)', max_length=150, null=True, unique=True, verbose_name='Sorozatszám'),
        ),
        migrations.AlterField(
            model_name='equipmenttipus',
            name='emoji',
            field=models.CharField(blank=True, help_text='Az eszköz típushoz tartozó emoji ikon (opcionális)', max_length=10, null=True, verbose_name='Emoji'),
        ),
        migrations.AlterField(
            model_name='equipmenttipus',
            name='name',
            field=models.CharField(help_text='Az eszköz típusának neve', max_length=150, unique=True, verbose_name='Típus neve'),
        ),
        migrations.AlterField(
            model_name='forgatas',
            name='contactPerson',
            field=models.ForeignKey(blank=True, help_text='A forgatáshoz tartozó kapcsolattartó személy', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.contactperson', verbose_name='Kapcsolattartó'),
        ),
        migrations.AlterField(
            model_name='forgatas',
            name='date',
            field=models.DateField(help_text='A forgatás dátuma', verbose_name='Dátum'),
        ),
        migrations.AlterField(
            model_name='forgatas',
            name='description',
            field=models.TextField(help_text='A forgatás részletes leírása (maximum 500 karakter)', max_length=500, verbose_name='Leírás'),
        ),
        migrations.AlterField(
            model_name='forgatas',
            name='equipments',
            field=models.ManyToManyField(blank=True, help_text='A forgatáshoz szükséges felszerelések', related_name='forgatasok', to='api.equipment', verbose_name='Felszerelések'),
        ),
        migrations.AlterField(
            model_name='forgatas',
            name='forgTipus',
            field=models.CharField(choices=[('kacsa', 'KaCsa'), ('rendes', 'Rendes'), ('rendezveny', 'Rendezvény'), ('egyeb', 'Egyéb')], help_text='A forgatás típusának kategóriája', max_length=150, verbose_name='Forgatás típusa'),
        ),
        migrations.AlterField(
            model_name='forgatas',
            name='location',
            field=models.ForeignKey(blank=True, help_text='A forgatás helyszíne (partnerintézmény)', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.partner', verbose_name='Helyszín'),
        ),
        migrations.AlterField(
            model_name='forgatas',
            name='name',
            field=models.CharField(help_text='A forgatás egyedi neve', max_length=150, verbose_name='Forgatás neve'),
        ),
        migrations.AlterField(
            model_name='forgatas',
            name='notes',
            field=models.TextField(blank=True, help_text='További megjegyzések a forgatáshoz (maximum 500 karakter)', max_length=500, null=True, verbose_name='Megjegyzések'),
        ),
        migrations.AlterField(
            model_name='forgatas',
            name='relatedKaCsa',
            field=models.ForeignKey(blank=True, help_text='A forgatáshoz kapcsolódó KaCsa típusú forgatás', limit_choices_to={'forgTipus': 'kacsa'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_forgatas', to='api.forgatas', verbose_name='Kapcsolódó KaCsa'),
        ),
        migrations.AlterField(
            model_name='forgatas',
            name='timeFrom',
            field=models.TimeField(help_text='A forgatás kezdési időpontja', verbose_name='Kezdés ideje'),
        ),
        migrations.AlterField(
            model_name='forgatas',
            name='timeTo',
            field=models.TimeField(help_text='A forgatás befejezésének időpontja', verbose_name='Befejezés ideje'),
        ),
        migrations.AlterField(
            model_name='osztaly',
            name='osztaly_fonokei',
            field=models.ManyToManyField(blank=True, help_text='Az osztályfőnök és helyettese', related_name='osztaly_fonokei', to=settings.AUTH_USER_MODEL, verbose_name='Osztályfőnökei'),
        ),
        migrations.AlterField(
            model_name='osztaly',
            name='startYear',
            field=models.IntegerField(help_text='Az év, amikor az osztály első alkalommal megkezdte tanulmányait', verbose_name='Indulási év'),
        ),
        migrations.AlterField(
            model_name='osztaly',
            name='szekcio',
            field=models.CharField(help_text='Az osztály szekciója (pl. F, A, B, stb.)', max_length=1, verbose_name='Szekció'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, help_text='A partner szervezet címe (maximum 500 karakter)', max_length=500, null=True, verbose_name='Cím'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='imgUrl',
            field=models.URLField(blank=True, help_text='A partnerhez tartozó kép webcíme (opcionális, maximum 1000 karakter)', max_length=1000, null=True, verbose_name='Kép URL'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='A partner intézmény típusa', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='api.partnertipus', verbose_name='Intézmény típusa'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(help_text='A partner szervezet vagy intézmény neve', max_length=150, unique=True, verbose_name='Partner neve'),
        ),
        migrations.AlterField(
            model_name='partnertipus',
            name='name',
            field=models.CharField(help_text='A partner típus neve (pl. Iskola, Múzeum, Vállalat, stb.)', max_length=150, unique=True, verbose_name='Típus neve'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='admin_type',
            field=models.CharField(choices=[('none', 'Nincs adminisztrátor jogosultság'), ('developer', 'Administrator-Developer'), ('teacher', 'Administrator-Teacher (Médiatanár)'), ('system_admin', 'Rendszeradminisztrátor')], default='none', help_text='A felhasználó adminisztrátori jogosultságainak típusa', max_length=20, verbose_name='Adminisztrátor típus'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_login_sent_at',
            field=models.DateTimeField(blank=True, help_text='Időpont, amikor az első bejelentkezési token ki lett küldve', null=True, verbose_name='Első bejelentkezés token küldve'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_login_token',
            field=models.CharField(blank=True, help_text='Token az első bejelentkezéshez és jelszó beállításához', max_length=255, null=True, verbose_name='Első bejelentkezés token'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medias',
            field=models.BooleanField(default=True, help_text='Jelöli, hogy a felhasználó médiás-e', verbose_name='Médiás-e?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='osztaly',
            field=models.ForeignKey(blank=True, help_text='A felhasználó osztálya', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.osztaly', verbose_name='Osztály'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='osztalyfonok',
            field=models.BooleanField(default=False, help_text='Jelöli, hogy a felhasználó osztályfőnök-e', verbose_name='Osztályfőnök'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password_set',
            field=models.BooleanField(default=False, help_text='Jelöli, hogy a felhasználó beállította-e már a jelszavát', verbose_name='Jelszó beállítva'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='radio_stab',
            field=models.ForeignKey(blank=True, help_text='A felhasználó rádiós stábja (9F diákok számára)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tagok', to='api.radiostab', verbose_name='Rádiós stáb'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='special_role',
            field=models.CharField(choices=[('none', 'Nincs különleges szerep'), ('production_leader', 'Gyártásvezető')], default='none', help_text='A felhasználó különleges szerepe a rendszerben', max_length=20, verbose_name='Különleges szerep'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stab',
            field=models.ForeignKey(blank=True, help_text='A felhasználó stábja', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tagok', to='api.stab', verbose_name='Stáb'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefonszam',
            field=models.CharField(blank=True, help_text='A felhasználó telefonszáma', max_length=20, null=True, verbose_name='Telefonszám'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='A profilhoz tartozó felhasználói fiók', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó'),
        ),
        migrations.AlterField(
            model_name='radiosession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Az összejátszás létrehozásának időpontja', verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='radiosession',
            name='date',
            field=models.DateField(help_text='Az összejátszás dátuma', verbose_name='Dátum'),
        ),
        migrations.AlterField(
            model_name='radiosession',
            name='description',
            field=models.TextField(blank=True, help_text='Az összejátszás leírása (opcionális, maximum 500 karakter)', max_length=500, null=True, verbose_name='Leírás'),
        ),
        migrations.AlterField(
            model_name='radiosession',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Az összejátszásban résztvevő felhasználók', related_name='radio_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Résztvevők'),
        ),
        migrations.AlterField(
            model_name='radiosession',
            name='radio_stab',
            field=models.ForeignKey(help_text='Az összejátszáshoz tartozó rádiós stáb', on_delete=django.db.models.deletion.CASCADE, to='api.radiostab', verbose_name='Rádiós stáb'),
        ),
        migrations.AlterField(
            model_name='radiosession',
            name='time_from',
            field=models.TimeField(help_text='Az összejátszás kezdési időpontja', verbose_name='Kezdés ideje'),
        ),
        migrations.AlterField(
            model_name='radiosession',
            name='time_to',
            field=models.TimeField(help_text='Az összejátszás befejezési időpontja', verbose_name='Befejezés ideje'),
        ),
        migrations.AlterField(
            model_name='radiostab',
            name='description',
            field=models.TextField(blank=True, help_text='A rádiós stáb részletes leírása (maximum 300 karakter)', max_length=300, null=True, verbose_name='Leírás'),
        ),
        migrations.AlterField(
            model_name='radiostab',
            name='name',
            field=models.CharField(help_text='A rádiós stáb neve', max_length=50, verbose_name='Stáb név'),
        ),
        migrations.AlterField(
            model_name='radiostab',
            name='team_code',
            field=models.CharField(choices=[('A1', 'A1 rádió csapat'), ('A2', 'A2 rádió csapat'), ('B3', 'B3 rádió csapat'), ('B4', 'B4 rádió csapat')], help_text='A rádiós csapat egyedi kódja (A1, A2, B3, B4)', max_length=2, unique=True, verbose_name='Csapat kód'),
        ),
        migrations.AlterField(
            model_name='stab',
            name='name',
            field=models.CharField(help_text='A stáb egyedi neve', max_length=50, unique=True, verbose_name='Stáb neve'),
        ),
        migrations.AlterField(
            model_name='szerepkor',
            name='ev',
            field=models.IntegerField(blank=True, help_text='Az évfolyam, amelyre a szerepkör vonatkozik (opcionális)', null=True, verbose_name='Év'),
        ),
        migrations.AlterField(
            model_name='szerepkor',
            name='name',
            field=models.CharField(help_text='A szerepkör egyedi neve', max_length=150, unique=True, verbose_name='Szerepkör neve'),
        ),
        migrations.AlterField(
            model_name='szerepkorrelaciok',
            name='szerepkor',
            field=models.ForeignKey(help_text='A hozzárendelt szerepkör', on_delete=django.db.models.deletion.CASCADE, to='api.szerepkor', verbose_name='Szerepkör'),
        ),
        migrations.AlterField(
            model_name='szerepkorrelaciok',
            name='user',
            field=models.ForeignKey(help_text='A szerepkört betöltő felhasználó', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó'),
        ),
        migrations.AlterField(
            model_name='tavollet',
            name='denied',
            field=models.BooleanField(default=False, help_text='Jelöli, hogy a távollét kérés el lett-e utasítva', verbose_name='Elutasítva'),
        ),
        migrations.AlterField(
            model_name='tavollet',
            name='end_date',
            field=models.DateField(help_text='A távollét záró dátuma', verbose_name='Záró dátum'),
        ),
        migrations.AlterField(
            model_name='tavollet',
            name='reason',
            field=models.TextField(blank=True, help_text='A távollét indoklása (opcionális, maximum 500 karakter)', max_length=500, null=True, verbose_name='Indoklás'),
        ),
        migrations.AlterField(
            model_name='tavollet',
            name='start_date',
            field=models.DateField(help_text='A távollét kezdő dátuma', verbose_name='Kezdő dátum'),
        ),
        migrations.AlterField(
            model_name='tavollet',
            name='user',
            field=models.ForeignKey(help_text='A távollétét jelző felhasználó', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó'),
        ),
    ]
