# Generated by Django 5.2.4 on 2025-08-16 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_absence_date_alter_absence_diak_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forgatas',
            name='riporter',
            field=models.ForeignKey(blank=True, help_text='A forgatás riportere', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Riporter'),
        ),
    ]
