# Generated by Django 5.2.4 on 2025-08-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_forgatas_riporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tavollet',
            name='approved',
            field=models.BooleanField(default=False, help_text='Jelöli, hogy a távollét kérés jóvá lett-e hagyva', verbose_name='Jóváhagyva'),
        ),
    ]
