# Generated by Django 5.2.4 on 2025-08-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_tavollet_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='auto_generated',
            field=models.BooleanField(default=True, help_text='Jelöli, hogy ez a hiányzás automatikusan lett-e létrehozva beosztás alapján', verbose_name='Automatikusan generált'),
        ),
    ]
