# Generated by Django 5.2.4 on 2025-08-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_auto_generated_to_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='context',
            field=models.CharField(blank=True, help_text='Rövid azonosító információ (pl. intézmény + szerepkör, maximum 100 karakter)', max_length=100, null=True, verbose_name='Kontextus'),
        ),
    ]
