# Generated by Django 5.2.4 on 2025-08-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_context_to_contactperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_login_sent_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_login_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='osztalyfonok',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password_set',
        ),
    ]
