# Generated by Django 5.2.4 on 2025-08-24 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_unnecessary_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atigazolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stab', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_radio_stab', models.CharField(blank=True, max_length=100, null=True)),
                ('new_stab', models.CharField(blank=True, max_length=100, null=True)),
                ('new_radio_stab', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atigazolas', to='api.profile')),
            ],
            options={
                'verbose_name': 'Átigazolas',
                'verbose_name_plural': 'Átigazolasok',
            },
        ),
    ]
