# Generated by Django 5.2.4 on 2025-08-24 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_atigazolas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atigazolas',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atigazolasok', to='api.profile'),
        ),
    ]
