# Generated by Django 5.2.4 on 2025-08-25 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_atigazolas_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profilok'},
        ),
        migrations.AlterField(
            model_name='atigazolas',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atigazolasok', to='api.profile'),
        ),
    ]
