# Generated by Django 5.2.4 on 2025-08-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_profile_options_alter_atigazolas_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tavollet',
            name='end_date',
            field=models.DateTimeField(help_text='A távollét záró időpontja (dátum és idő)', verbose_name='Záró időpont'),
        ),
        migrations.AlterField(
            model_name='tavollet',
            name='start_date',
            field=models.DateTimeField(help_text='A távollét kezdő időpontja (dátum és idő)', verbose_name='Kezdő időpont'),
        ),
    ]
