# Generated by Django 5.2.4 on 2025-08-27 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_tavollet_end_date_alter_tavollet_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beosztas',
            name='stab',
            field=models.ForeignKey(blank=True, help_text='A beosztáshoz tartozó stáb', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beosztasok', to='api.stab', verbose_name='Stáb'),
        ),
    ]
