# Generated by Django 5.2.4 on 2025-09-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_stab_to_beosztas'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='szerkeszto',
            field=models.BooleanField(default=False, help_text='Jelöli, hogy a felhasználó kiírhat-e forgatásokat', verbose_name='Szerkesztő'),
        ),
    ]
