# Generated by Django 5.2.4 on 2025-09-16 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_profile_szerkeszto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgatas',
            name='riporter',
        ),
        migrations.AddField(
            model_name='forgatas',
            name='szerkeszto',
            field=models.ForeignKey(blank=True, help_text='A forgatás szerkesztője', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Szerkesztő'),
        ),
    ]
