# Generated by Django 5.2.4 on 2025-09-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_riporter_to_szerkeszto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A rendszerüzenet címe (maximum 200 karakter)', max_length=200, verbose_name='Cím')),
                ('message', models.TextField(help_text='A rendszerüzenet tartalma (maximum 2000 karakter)', max_length=2000, verbose_name='Üzenet')),
                ('showFrom', models.DateTimeField(help_text='Az üzenet megjelenítésének kezdő időpontja', verbose_name='Megjelenítés kezdete')),
                ('showTo', models.DateTimeField(help_text='Az üzenet megjelenítésének záró időpontja', verbose_name='Megjelenítés vége')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='A rendszerüzenet létrehozásának időpontja', verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='A rendszerüzenet utolsó módosításának időpontja', verbose_name='Módosítva')),
            ],
            options={
                'verbose_name': 'Rendszerüzenet',
                'verbose_name_plural': 'Rendszerüzenetek',
                'ordering': ['-showFrom'],
            },
        ),
    ]
