# Generated by Django 5.2.4 on 2025-09-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_systemmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessage',
            name='messageType',
            field=models.CharField(choices=[('user', 'Felhasználó'), ('developer', 'Fejlesztő'), ('operator', 'Operátor'), ('support', 'Támogatás')], default='user', help_text='Az üzenet célközönsége (user/developer/operator/support)', max_length=20, verbose_name='Üzenet típusa'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='severity',
            field=models.CharField(choices=[('info', 'Információ'), ('warning', 'Figyelmeztetés'), ('error', 'Hiba')], default='info', help_text='Az üzenet súlyossága (info/warning/error)', max_length=20, verbose_name='Súlyosság'),
        ),
    ]
