# Generated by Django 5.2.4 on 2025-09-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_systemmessage_messagetype_systemmessage_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='student_edit_note',
            field=models.TextField(blank=True, help_text='A diák által megadott indoklás az extra időre (maximum 500 karakter)', max_length=500, null=True, verbose_name='Diák megjegyzés'),
        ),
        migrations.AddField(
            model_name='absence',
            name='student_edit_timestamp',
            field=models.DateTimeField(blank=True, help_text='Mikor módosította a diák utoljára a hiányzást', null=True, verbose_name='Diák szerkesztés időpontja'),
        ),
        migrations.AddField(
            model_name='absence',
            name='student_edited',
            field=models.BooleanField(default=False, help_text='Jelöli, hogy a diák módosította-e a hiányzás adatait', verbose_name='Diák által szerkesztett'),
        ),
        migrations.AddField(
            model_name='absence',
            name='student_extra_time_after',
            field=models.IntegerField(default=0, help_text='A diák által megadott extra idő percben a forgatás után', verbose_name='Diák által beküldött extra idő utána (perc)'),
        ),
        migrations.AddField(
            model_name='absence',
            name='student_extra_time_before',
            field=models.IntegerField(default=0, help_text='A diák által megadott extra idő percben a forgatás előtt', verbose_name='Diák által beküldött extra idő előtte (perc)'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='auto_generated',
            field=models.BooleanField(default=True, help_text='Jelöli, hogy ez a hiányzás automatikusan lett-e létrehozva beosztás alapján. Ha ez a mező hamis, az azt jelenti, hogy a hiányzást egy diák kézi kiegészítése.', verbose_name='Automatikusan generált'),
        ),
    ]
