# Generated by Django 5.2.4 on 2025-09-26 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_student_absence_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TavolletTipus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A távolléti típus neve (pl. betegség, iskolai elfoglaltság, stb.)', max_length=150, unique=True, verbose_name='Típus neve')),
                ('explanation', models.TextField(blank=True, help_text='A típus részletes magyarázata és konkrét példák (maximum 1000 karakter)', max_length=1000, null=True, verbose_name='Magyarázat/Példák')),
                ('ignored_counts_as', models.CharField(choices=[('approved', 'Jóváhagyottnak számít'), ('denied', 'Elutasítottnak számít')], default='approved', help_text='Meghatározza, hogy ha a típus figyelmen kívül van hagyva, jóváhagyottnak vagy elutasítottnak számít-e', max_length=10, verbose_name='Figyelmen kívül hagyáskor számít mint')),
            ],
            options={
                'verbose_name': 'Távolléti Típus',
                'verbose_name_plural': 'Távolléti Típusok',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tavollet',
            name='tipus',
            field=models.ForeignKey(blank=True, help_text='A távollét típusa (betegség, iskolai elfoglaltság, stb.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tavollettipus', verbose_name='Távolléti típus'),
        ),
    ]
