# Generated by Django 5.2.4 on 2025-12-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_tavollettipus_tavollet_tipus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tavollet',
            name='teacher_reason',
            field=models.TextField(blank=True, help_text='A tanár által megadott indoklás a jóváhagyás vagy elutasítás okáról (opcionális, maximum 500 karakter)', max_length=500, null=True, verbose_name='Tanári indoklás'),
        ),
    ]
