# Generated by Django 5.2.4 on 2026-03-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_tavollet_teacher_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tavollet',
            name='teacher_reason',
        ),
    ]
