# Generated by Django 5.1.15 on 2026-07-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_tavollet_teacher_reason'),
    ]

    operations = [
        # Data migration: preserve the existing Osztaly -> Tanev link by
        # copying it into the Tanev.osztalyok M2M relation before dropping
        # the FK field. This ensures no information is lost.
        migrations.RunPython(
            code=lambda apps, schema_editor: _copy_osztaly_tanev_to_m2m(apps),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='osztaly',
            name='tanev',
        ),
    ]


def _copy_osztaly_tanev_to_m2m(apps):
    Osztaly = apps.get_model('api', 'Osztaly')
    for osztaly in Osztaly.objects.exclude(tanev__isnull=True):
        osztaly.tanev.osztalyok.add(osztaly)

