# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_tavollet_teacher_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='elrejtve',
            field=models.BooleanField(default=False, help_text='Ha be van jelölve, a felhasználó nem jelenik meg a Stáb oldal listájában', verbose_name='Elrejtve a Stáb oldalon'),
        ),
    ]
