# Generated by Django 5.2.4 on 2026-09-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_profile_elrejtve'),
        ('api', '0035_remove_osztaly_tanev_field'),
    ]

    operations = [
    ]
