# Generated by Django 5.2.4 on 2026-09-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_forgatas_start_time_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiostab',
            name='team_code',
            field=models.CharField(choices=[('A1', 'A1 rádió csapat'), ('A2', 'A2 rádió csapat'), ('B3', 'B3 rádió csapat'), ('B4', 'B4 rádió csapat')], help_text='A rádiós csapat egyedi kódja (A1, A2, B3, B4)', max_length=2, verbose_name='Csapat kód'),
        ),
    ]
